#Server name
ShortCode: 'S'
ServerName: 'Survival'

#Default channel and listen
defaultChannel: 'S'
defaultListen: [S, Server, Global]

#Multi server config
multiServer: false
chatServer: ''
chatServerPassword: ''

#Log chat to console
consoleLogChat: true
#Log chat from other servers
consoleLogServers: true
#Log other server info, Such as player joins and dis/connects from chatserver
consoleLogServerInfo: true

#Display or hide the playerlist on join 
hideJoinPlayerList: false
#Display the welcome message for new players
displayWelcome: true

#Console sender used when using /say
consoleSender-colour: '&4'
consoleSender: CONSOLE

strings:
  player-welcome: '&aWelcome &e%player% &ato the server!'
  player-join: '%prefix%%player% &ehas joined %server%!'
  player-quit: '%prefix%%player% &ehas left %server%!'
  message: '&f<&3%server%&7%channel%&f>%prefix% %player%: &7%message%'
  action: '&f<&3%server%&7%channel%&f> * %prefix%%player% &f%message%'
  pm_send: '&7(to %to%) %message%' # you can also use %from%
  pm_receive: '&7(from %from%) %message%' # you can also use %to%
  timeout-mod: '%prefix%%player% %fHas been put in timeout for %time% minutes'
  timeout-player: 'You have been placed in timeout for %time% seconds'
  timeout-players: '%prefix%%player% &fHas been put in timeout for %time% minutes'
  timeout-reason: 'For %reason%'
  networkMessage: '&cNetwork Message: %message%'